### ISSUE TITLE
image support

### ISSUE THREAD

**Issue by sylvest99js** [vigou3/emacs-modified-windows#2]
I believe there is an issue with image support, at least for jpegs. dynamic-library-alist has the entry (jpeg "libjpeg-8.dll"), while the bin directory contains libjpeg-9.dll . Sorry I don't know how to fix this myself, or even if this is related to your modification or the version  of emacs.

Thanks for your help. I have been using your emacs modified for many years, and will take this opportunity to say thanks.

**Comment by vigou3** [comment]
Good catch! I just released a fixed version that includes libjpeg-8.dll instead of libjpeg-9.dll.
