### ISSUE TITLE
Nuking trailing whitespace

### ISSUE THREAD

**Issue by memmett** [vigou3/emacs-modified-windows#4]
Hello,

I've noticed that trailing whitespace started getting nuked recently. Usually I prefer this behaviour, but sometimes it creates a lot of noise for commits in multi-developer projects. I found that, in `site-start.el`, `ess-nuke-trailing-whitespace` gets added to `write-file-functions` in `ess-mode-hook`. Would it be possible to make this buffer local?  For now I will disable this.

Usually I live in Fortran land but when I run R through ORG mode, then all my trailing whitespace starts getting nuked globally (including in Fortran files). I guess my R snippets in ORG mode are triggering `ess-mode-hook`.

PS, thank you for all your efforts on bringing a smooth Emacs experience to Windows.

**Comment by vigou3** [comment]
This was changed in version 25.2-modified-1. As per NEWS:

## User visible changes

- In `site-start.el`, `ess-nuke-trailing-whitespace` is now added to
  the `write-contents-functions` hook to avoid bleeding of the
  functionality to other major modes (most notably markdown, where
  trailing whitespace is sometimes useful).

From my understanding of `write-contents-functions`, this should be buffer local.

Thanks for the kind words!
