### ISSUE TITLE
R 3.4.1 has R but no Rterm: Emacs cannot find R

### ISSUE THREAD

**Issue by taqtiqa-mark** [vigou3/emacs-modified-windows#5]
Hi, Thank you for all your effort on providing these builds!
This may be due to a change in the R build.
Installing R 3.4.1 and adding the folder to the User's path results in:
1) cmd.exe:
````
C:\> where R
C:\Users\<user>\AppData\Roaming\R\R-3.4.1\bin\R.exe
C:\> where Rterm
Could not find file for the given patterns
````
2) Emacs (GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24)
````
Finding all versions of R on your system...
Sorry, no version of R could be found on your system.
````
Hope that helps?

**Comment by vigou3** [comment]
Thanks for the kind words. If there was something to report it'd be upstream to the ESS team. That said, the behaviour is as expected: ESS will find R versions on Windows when they are installed in the usual default locations; see section 12.2 of the ESS manual. With your setup, you will have to inform ESS or Emacs where to find R.
