### ISSUE TITLE
Imagemagick support

### ISSUE THREAD

**Issue by jingxlim** [vigou3/emacs-modified-windows#6]
Hey Vincent, really great work coming up with this distribution. I've had the most success with getting things to work on Windows after I started using this.

Recently, I've been trying to write reports on Org mode and noticed that resizing inline images doesn't work. I understand that imagemagick is required for this and from reading the installations notes, that your distribution does work with Imagemagick, which I do have installed. I also have its directory in my PATH environment variable. Running `(image-type-available-p 'imagemagick)` however returns `nil`, so I wonder what's missing.

Do you have any advice on this?

**Comment by jingxlim** [comment]
I found a distribution that is compiled with Imagemagick (https://www.reddit.com/r/emacs/comments/8n2wga/emax6420180529_261_final_released/). I've tried it and it works well with resizing inline images in Org. I'm reluctant to switch as I've very much gotten used to your distribution and use latex heavily.

Any chance you would be interested in looking into this? I wish I knew a bit more about compiling and elisp so that I could help, but I unfortunately don't...

**Comment by vigou3** [comment]
I'm sure you'll understand that I will not base by distribution on one found on Reddit. ;-)

If you want to my add my extensions to this distribution, though, you can clone the GitHub repository and most likely only adapt the Makeconf file for the name of the distribution and remove 'get-emacs' from the 'get-packages' recipe in the Makefile (line 58). Then follow the instructions in README.md (found on the GitHub repository).

We'll see if emacs-w64 includes ImageMagick support with the new release 26.1. It is not out yet.

v.
