### ISSUE TITLE
Slow launch

### ISSUE THREAD

**Issue by rbchan** [vigou3/emacs-modified-windows#8]
I just installed your distribution of Emacs Modified for Windows, and it is taking much longer to launch than it did when I last installed it (approximately 2 years ago). Here is what I see:

```
rbchan@FOR-3-409b MINGW64 ~
$ time emacs -batch -q
real    0m14.230s
user    0m0.000s
sys     0m0.031s
```

Is this normal, or is there something I can do to speed it up?

**Comment by vigou3** [comment]
I didn't notice anything special at my end. The latest release is a major Emacs revision (26.1), so perhaps that's the direction you should be looking at. The distribution being based on the official GNU binaries, maybe you can try the latter to see if it makes a difference on launch time.

**Comment by rbchan** [comment]
I tried the released based on 25.2 and it was also slow to launch. Simplifying my init file didn't help either, so I wonder if it has something to do with the `site-start.el`  or the `default.el` file because it launches very quickly with the -Q flag:

```
$ time emacs -batch -Q
real    0m2.237s
user    0m0.015s
sys     0m0.046s
```

**Comment by rbchan** [comment]
I'm working around this by using `runemacs --daemon` before `emacsclient FILE`.

**Comment by vigou3** [comment]
Just for completeness...

First, apologies for remaining silent a few days: the license for my Windows virtual machine had expired.

Let's see what I get issuing the same commands as you.

```
$ time /c/Program\ Files/GNU\ Emacs\ 26.1/bin/emacs -batch -Q

real    0m0,047s
user    0m0,000s
sys     0m0,000s
```
and 
```
$ time /c/Program\ Files/GNU\ Emacs\ 26.1/bin/emacs -batch -q
Finding all versions of R on your system...

real    0m1,978s
user    0m0,000s
sys     0m0,015s
```

The difference (and long startup time for you) might be in good part explained by ESS searching for installed versions of R. Do you have a non standard installation of R --- or none at all?

**Comment by rbchan** [comment]
Thanks for getting back to me. I have R installed here: `C:/R/R-3.3.1/`, and I have this on my PATH: `C:/R/R-3.3.1/bin/x64`. This seems to be fine because I can run Rterm from the command line like so:

```
$ time Rterm -q -e "q('no')"
> q('no')
real    0m1.229s
user    0m0.015s
sys     0m0.062s
```

R also starts properly within emacs using `M-x R`. Is there something wrong with installing R in `C:/R/`?

**Comment by vigou3** [comment]
Nothing wrong per se, but ESS might have trouble finding R. Try to move R to the standard location `C:\Program Files` and see if it speeds up startup. You may also have a look at the `*Messages*` buffer immediately after Emacs has started to see if there are any error messages.

**Comment by rbchan** [comment]
That didn't work either, and there are no error messages in `*Messages*`. However, if I comment out all ESS related code in `site-start.el` and `.emacs` it starts up quickly. I'm still unsure why ESS would take so long to load.

**Comment by vigou3** [comment]
Then I think I'm out of suggestions, other than posting to [ess-help](https://stat.ethz.ch/mailman/listinfo/ess-help) where Emacs and ESS gurus may help you tracking down the problem.
